name: MSBuild

on:
  push:
    branches:
      - develop
      - mod

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release_MD
  # PLATFORM_TARGET: x64
  PLATFORM_TOOLSET: v143
  PLATFORM_VERSION: 10.0.22621.0

jobs:
  build:
    strategy:
      matrix:
        PLATFORM_TARGET: [x64, Win32]

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    # - uses: ilammy/msvc-dev-cmd@v1
    #   with:
    #     arch: ${{ matrix.PLATFORM_TARGET }}

    # - name: Restore NuGet packages
    #  working-directory: ${{ github.workspace }}
    #  run: nuget restore ${{ env.SOLUTION_FILE_PATH }}

    # - name: Update submodule
    #  run: git submodule update --remote

    - name: Build LibISDB
      working-directory: ${{ github.workspace }}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: |
        echo "sed -i -e 's/|x86/|Win32/g' src/LibISDB/Projects/LibISDB.sln" |bash
        msbuild src\LibISDB\Projects\LibISDB.sln -m -t:build -p:Configuration=${{ env.BUILD_CONFIGURATION }} -p:Platform=${{ matrix.PLATFORM_TARGET }} -p:PlatformToolset=${{ env.PLATFORM_TOOLSET }} -p:WindowsTargetPlatformVersion=${{ env.PLATFORM_VERSION }}

    - name: Build TVTest
      working-directory: ${{ github.workspace }}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild src\TVTest.sln -m -t:build -p:Configuration=${{ env.BUILD_CONFIGURATION }} -p:Platform=${{ matrix.PLATFORM_TARGET }} -p:PlatformToolset=${{ env.PLATFORM_TOOLSET }} -p:WindowsTargetPlatformVersion=${{ env.PLATFORM_VERSION }}

    - name: Build TVTest Samples
      working-directory: ${{ github.workspace }}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild sdk\Samples\Samples.sln -m -t:build -p:Configuration=Release -p:Platform=${{ matrix.PLATFORM_TARGET }} -p:PlatformToolset=${{ env.PLATFORM_TOOLSET }} -p:WindowsTargetPlatformVersion=${{ env.PLATFORM_VERSION }}

    # - name: compile TVTest.chm
    #  working-directory: ${{ github.workspace }}/src/Help
    #  shell: cmd
    #  run: |
    #    hhc TVTest.hhp
    #    copy /v /y TVTest.chm ..\..\data

    - name: run package.sh
      working-directory: ${{ github.workspace }}
      shell: bash
      run: |
        sed -i -e '/^if \[ "$arch"/s/x86/Win32/gi' package.sh
        ./package.sh -a ${{ matrix.PLATFORM_TARGET }} -c dynamic -l all -r bz2 -t release

    - name: list files
      run: ls package

    # Upload package: https://github.com/marketplace/actions/upload-artifact
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TVTest ${{ matrix.PLATFORM_TARGET }} ${{ env.BUILD_CONFIGURATION }} build
        path: package\TVTest*_${{ matrix.PLATFORM_TARGET }}.tar.bz2
        compression-level: 0
